```{r}
library(tidyverse)
library(openintro)
```

```{r}
#Takes a long time to run would recommmend only running once  
severityDS <- read.csv("Severity.csv")
start_timeDS <- read.csv("Start_Time.csv")
end_timeDS <- read.csv("End_Time.csv")
latDS <- read.csv("Start_Lat.csv")
longDS <- read.csv("Start_Lng.csv")
cityDS <- read.csv("City.csv")
countyDS <- read.csv("County.csv")
stateDS <- read.csv("State.csv")
tempDS <- read.csv("Temperature.csv")
windDS <- read.csv("Wind_Speed.csv")
visibiltyDS <- read.csv( "Visibilty.csv")
startDayDS <- read.csv("Start_Day.csv")
startYearDS <- read.csv("Start_Year.csv")
startMonthDS <- read.csv("Start_Month.csv")
endDayDS <- read.csv("End_Day.csv")
endYearDS <- read.csv("End_Year.csv")
endMonthDS <- read.csv("End_Month.csv")
```

```{r}
#Joins all the data together will add more if we need more columns
#Takes a long time to run would recommmend only running once  
fullData <- severityDS %>%
  inner_join(start_timeDS) %>%
  inner_join(end_timeDS) %>%
  inner_join(latDS) %>%
  inner_join(longDS) %>%
  inner_join(cityDS) %>%
  inner_join(countyDS) %>%
  inner_join(stateDS) %>%
  inner_join(tempDS) %>%
  inner_join(windDS) %>%
  inner_join(visibiltyDS) %>%
  inner_join(startMonthDS) %>%
  inner_join(startYearDS) %>%
  inner_join(startDayDS) %>%
  inner_join(endYearDS) %>%
  inner_join(endDayDS) %>%
  inner_join(endMonthDS) %>%
  select(-X) #deletes a column that is row number
```

```{r}
#use a sub set of the data to test things
Iowa <- fullData %>%
  filter(State == "IA")
```

```{r}
library(maps)
```

```{r}
IAcounties <- map_data("county") %>%
  filter(region == "iowa") 

IACleanData <- Iowa %>%
  mutate(region = "iowa") %>%
  mutate(subregion = tolower(County)) %>%
  select(region, subregion,Severity) %>%
  group_by(region,subregion) %>%
  summarise(meanSeverity = mean(Severity)) %>%
  right_join(IAcounties,by=c("region","subregion"))

ggplot(IACleanData, aes(x=long,y=lat,fill = meanSeverity))+
  geom_polygon(aes(group=group))+
  scale_fill_continuous(type = "viridis")+
  labs(x="Longitude",y="Latitude",title = "Severity of Accidents in Iowa by County")


```

```{r}
#plots the mean severity in every county in the us altough it appears some counites are missing
fullCounties <- map_data("county")


meanSeverityMap <- fullData %>% 
  mutate(region = tolower(abbr2state(State))) %>%
  mutate(subregion = tolower(County)) %>%
  select(region, subregion,Severity) %>%
  group_by(region,subregion) %>%
  summarise(meanSeverity = mean(Severity)) %>%
  right_join(fullCounties,by=c("region","subregion"))

accidentLocationPlot <- fullData %>%
  select(Start_Lat,Start_Lng)
  
ggplot(fullCounties,aes(x=long,y=lat)) +
  geom_polygon(aes(group=group)) +
  geom_point(data= accidentLocationPlot,
             aes(x=Start_Lng,y=Start_Lat),
             color='red', 
             alpha=0.5, 
             size=0.02)+ 
  xlab("Longitude") + 
  ylab("Latitude") + 
  labs(title = "Accdient Locations by Longitude and Latitude")


ggplot(meanSeverityMap, aes(x=long,y=lat,fill = meanSeverity))+
  geom_polygon(aes(group=group)) +
  scale_fill_continuous(type = "viridis")+
  labs(x="Longitude",y="Latitude",title = "Severity of Accidents in US by County")
  
```

```{r}
#Doing things with duration and whatnot
library(lubridate)
IADuration <- Iowa %>%
  unite(col = "Start_Date", c(Start_Year,Start_Month,Start_Day),sep = "-") %>%
  unite(col = "FullStart_Time", c(Start_Date,Start_Time),sep = " ") %>%
  unite(col = "End_Date", c(End_Year,End_Month,End_Day),sep = "-") %>%
  unite(col = "FullEnd_Time", c(End_Date,End_Time),sep = " ") %>%
  mutate(duration = as.double(as.duration(interval(ymd_hms(FullStart_Time),ymd_hms(FullEnd_Time)))))%>% #num of seconds of the accident
  mutate(Severity = factor(Severity))
  
ggplot(IADuration,aes(x=Severity, y=duration)) +
  geom_boxplot()

ggplot(IADuration, aes(x=Severity, y = Temperature.F.)) +
  geom_boxplot()

ggplot(IADuration, aes(x=Severity, y = Wind_Speed.mph.)) +
  geom_boxplot()
```


```{r}
Full_Duration <- fullData %>%
  unite(col = "Start_Date", c(Start_Year,Start_Month,Start_Day),sep = "-") %>%
  unite(col = "FullStart_Time", c(Start_Date,Start_Time),sep = " ") %>%
  unite(col = "End_Date", c(End_Year,End_Month,End_Day),sep = "-") %>%
  unite(col = "FullEnd_Time", c(End_Date,End_Time),sep = " ") %>%
  mutate(duration = as.double(as.duration(interval(ymd_hms(FullStart_Time),ymd_hms(FullEnd_Time))))) %>%
  mutate(Severity = factor(Severity))

ggplot(Full_Duration,aes(x=Severity, y=duration)) +
  geom_boxplot()

ggplot(Full_Duration, aes(x=Severity, y = Temperature.F.)) +
  geom_boxplot() 

ggplot(Full_Duration, aes(x=Severity, y = Wind_Speed.mph.)) +
  geom_boxplot()+ 
  ylim(c(0,100))
```
