---
output: html_document
---

```{r}
library(tidyverse)
library(openintro)
library(lubridate)
library(maps)
library(scales)
```

```{r}
#Takes a long time to run would recommmend only running once  
severityDS <- read.csv("Severity.csv")
start_timeDS <- read.csv("Start_Time.csv")
end_timeDS <- read.csv("End_Time.csv")
latDS <- read.csv("Start_Lat.csv")
longDS <- read.csv("Start_Lng.csv")
cityDS <- read.csv("City.csv")
countyDS <- read.csv("County.csv")
stateDS <- read.csv("State.csv")
tempDS <- read.csv("Temperature.csv")
windDS <- read.csv("Wind_Speed.csv")
visibiltyDS <- read.csv( "Visibilty.csv")
startDayDS <- read.csv("Start_Day.csv")
startYearDS <- read.csv("Start_Year.csv")
startMonthDS <- read.csv("Start_Month.csv")
endDayDS <- read.csv("End_Day.csv")
endYearDS <- read.csv("End_Year.csv")
endMonthDS <- read.csv("End_Month.csv")
```

```{r}
#Code already in project code file

#Joins all the data together will add more if we need more columns
#Takes a long time to run would recommmend only running once  
fullData <- severityDS %>%
  inner_join(start_timeDS) %>%
  inner_join(end_timeDS) %>%
  inner_join(latDS) %>%
  inner_join(longDS) %>%
  inner_join(cityDS) %>%
  inner_join(countyDS) %>%
  inner_join(stateDS) %>%
  inner_join(tempDS) %>%
  inner_join(windDS) %>%
  inner_join(visibiltyDS) %>%
  inner_join(startMonthDS) %>%
  inner_join(startYearDS) %>%
  inner_join(startDayDS) %>%
  inner_join(endYearDS) %>%
  inner_join(endDayDS) %>%
  inner_join(endMonthDS) %>%
  select(-X) #deletes a column that is row number

Full_Duration <- fullData %>%
  unite(col = "Start_Date", c(Start_Year,Start_Month,Start_Day),sep = "-") %>%
  unite(col = "FullStart_Time", c(Start_Date,Start_Time),sep = " ") %>%
  unite(col = "End_Date", c(End_Year,End_Month,End_Day),sep = "-") %>%
  unite(col = "FullEnd_Time", c(End_Date,End_Time),sep = " ") %>%
  mutate(duration = as.double(as.duration(interval(ymd_hms(FullStart_Time),ymd_hms(FullEnd_Time))))) #num of seconds of the accident

fullCounties <- map_data("county")
```

```{r, fig.width=10}
durationMapData <- Full_Duration %>% mutate(subregion=tolower(County), region=tolower(abbr2state(State))) %>% select(subregion, region, duration) %>% group_by(subregion,region) %>% summarize(medianDuration = median(duration)) %>% mutate(durationFactor = ifelse(medianDuration<1200,1,
                                              ifelse(medianDuration<2400, 2,
                                              ifelse(medianDuration<3600, 3,
                                              ifelse(medianDuration<4800, 4,
                                              ifelse(medianDuration<6000, 5, 6)))))) 
durationMapData$durationFactor <- as.factor(durationMapData$durationFactor)
colors <- c("steelblue1","steelblue2","steelblue3", "steelblue4","royalblue4","navyblue")
durationMapData %>% right_join(fullCounties, by=c("subregion","region")) %>% ggplot(aes(x=long,y=lat, fill=durationFactor)) + geom_polygon(aes(group=group)) + scale_fill_manual(name="Median Duration (min)", values=colors, labels=c("<20","20-40","40-60","60-80","80-100",">100")) +labs(title="Median Accident Duration by Location", x="Longitude", y="Latitude")



fullData %>% group_by(Severity) %>% summarize(c=n())

FullWeather <- fullData %>% mutate(relativeTemp = ifelse(Temperature.F. <= 20, "<20",
                                                 ifelse(Temperature.F. <= 40, "20-40", 
                                                 ifelse(Temperature.F. <= 60, "40-60",
                                                 ifelse(Temperature.F. <= 80, "60-80", ">80")))))
FullWeather <- FullWeather %>% mutate(relWind = ifelse(Wind_Speed.mph. <= 5, "<=5 mph",
                                                ifelse(Wind_Speed.mph. <= 10, "5-10 mph",
                                                ifelse(Wind_Speed.mph. <= 15, "10-15 mph", ">15 mph"))))

FullWeather$relativeTemp <- as.factor(FullWeather$relativeTemp)
FullWeather$relativeTemp <- factor(FullWeather$relativeTemp, levels=c("<20","20-40","40-60","60-80",">80"))
FullWeather$relWind <- as.factor(FullWeather$relWind)
FullWeather$relWind <- factor(FullWeather$relWind, levels=c("<=5 mph", "5-10 mph", "10-15 mph", ">15 mph"))
FullWeather$Severity <- as.factor(FullWeather$Severity)

FullWeather %>% filter(!is.na(relativeTemp) & !is.na(relWind)) %>%  ggplot(aes(x=relativeTemp, fill=Severity)) + geom_bar(position="stack") + labs(title= "Weather Conditions vs Frequency and Severity of Accidents", x="Temperature (F)", y="Number of Accidents") + facet_wrap(~relWind) + scale_y_continuous(labels=unit_format(unit="K", scale=1e-3)) + scale_fill_manual(values=c("goldenrod","steelblue2","steelblue3", "steelblue4"))

FullWeather$relativeTemp <- factor(FullWeather$relativeTemp, levels= rev(levels(FullWeather$relativeTemp)))

FullWeather %>% filter(!is.na(relativeTemp) & !is.na(relWind)) %>% ggplot(aes(x=Severity, fill=relativeTemp, y=1)) + geom_bar(stat="identity", position="fill") + facet_wrap(~relWind) + scale_fill_manual(values = c("goldenrod","steelblue1", "steelblue2","steelblue3", "steelblue4")) + labs(title="Weather vs Severity of Accidents", y="Temperature Proportion (%)")
```


References:
- colors from: http://sape.inf.usi.ch/quick-reference/ggplot2/colour

- https://stackoverflow.com/questions/52602503/display-an-axis-value-in-millions-in-ggplot 