---
title: "Final Project"
author: "Eric Gleiter, Anyesha Ray, Brandon Xicon, Mckenna Goffinet"
date: "4/6/2020"
output: html_document
---

**PLACE HOLDER FOR NOW**
```{r}
if (!require("tidyverse")) {
install.packages("tidyverse")
}
if (!require("openintro")) {
install.packages("openintro")
}
if (!require("lubridate")) {
install.packages("lubridate")
}
if (!require("maps")) {
install.packages("maps")
}
if (!require("plotly")) {
install.packages("plotly")
}
library(plotly)
library(tidyverse)
library(openintro) #used to quickly switch state names and abbrevations
library(maps)
library(lubridate)
```


```{r}
#Takes a long time to run would recommmend only running once  
severityDS <- read.csv("Severity.csv")
start_timeDS <- read.csv("Start_Time.csv")
end_timeDS <- read.csv("End_Time.csv")
latDS <- read.csv("Start_Lat.csv")
longDS <- read.csv("Start_Lng.csv")
cityDS <- read.csv("City.csv")
countyDS <- read.csv("County.csv")
stateDS <- read.csv("State.csv")
tempDS <- read.csv("Temperature.csv")
windDS <- read.csv("Wind_Speed.csv")
visibiltyDS <- read.csv( "Visibilty.csv")
startDayDS <- read.csv("Start_Day.csv")
startYearDS <- read.csv("Start_Year.csv")
startMonthDS <- read.csv("Start_Month.csv")
endDayDS <- read.csv("End_Day.csv")
endYearDS <- read.csv("End_Year.csv")
endMonthDS <- read.csv("End_Month.csv")
```

```{r}
#Joins all the data together will add more if we need more columns
#Takes a long time to run would recommmend only running once  
fullData <- severityDS %>%
  inner_join(start_timeDS) %>%
  inner_join(end_timeDS) %>%
  inner_join(latDS) %>%
  inner_join(longDS) %>%
  inner_join(cityDS) %>%
  inner_join(countyDS) %>%
  inner_join(stateDS) %>%
  inner_join(tempDS) %>%
  inner_join(windDS) %>%
  inner_join(visibiltyDS) %>%
  inner_join(startMonthDS) %>%
  inner_join(startYearDS) %>%
  inner_join(startDayDS) %>%
  inner_join(endYearDS) %>%
  inner_join(endDayDS) %>%
  inner_join(endMonthDS) %>%
  select(-X) #deletes a column that is row number
```

```{r}
#use a sub set of the data to test things
Iowa <- fullData %>%
  filter(State == "IA")
```


```{r}
#plots the mean severity in every county in the us altough it appears some counites are missing
fullCounties <- map_data("county")


fullMapData <- fullData %>% 
  mutate(region = tolower(abbr2state(State))) %>%
  mutate(subregion = tolower(County)) %>%
  select(region, subregion,Severity) %>%
  group_by(region,subregion) %>%
  summarise(meanSeverity = mean(Severity)) %>%
  right_join(fullCounties,by=c("region","subregion"))

ggplot(fullMapData, aes(x=long,y=lat,fill = meanSeverity))+
  geom_polygon(aes(group=group)) +
  labs(x="Longitude",y="Latitude",title = "Severity of Accidents in US by County")

```

```{r}
#The following reconverts all the date and time columns back together and get a numeric duration for the accident
Full_Duration <- fullData %>%
  unite(col = "Start_Date", c(Start_Year,Start_Month,Start_Day),sep = "-") %>%
  unite(col = "FullStart_Time", c(Start_Date,Start_Time),sep = " ") %>%
  unite(col = "End_Date", c(End_Year,End_Month,End_Day),sep = "-") %>%
  unite(col = "FullEnd_Time", c(End_Date,End_Time),sep = " ") %>%
  mutate(duration = as.double(as.duration(interval(ymd_hms(FullStart_Time),ymd_hms(FullEnd_Time))))) #num of seconds of the accident


ggplot(Full_Duration,aes(x=Severity, y=duration)) +
  geom_point()

```


```{r}
#decided to get rid of he data from 2016,2015 and 2020 in order to have data that includes full years as before the 2016 data starts in february which means january will be underrepresented
time<-fullData %>%
  filter(Start_Year!=2016)%>%
  filter(Start_Year!=2015)%>%
  filter(Start_Year!=2020)%>%
  unite(col = "Start_Date2", c(Start_Year,Start_Day,Start_Month),sep = "-",remove=FALSE)%>%
  group_by(Start_Date2) %>%
  mutate(dayCount = n())
#plotted the months to see which months were the most hazardous
ggplot(time,aes(x=Start_Month))+geom_bar()+labs(x="Month",title = "Frequency of accidents by month")+ scale_x_continuous(name = " ", breaks = c(1,2,3,4,5,6,7,8,9,10,11,12))
#got the distinct days so that we do not have to wait 5 years to load the data and to ensure the data does not overlap
 time<-time %>%
   distinct(Start_Date2,.keep_all = TRUE)

```


```{r}
#got the different days accident count to start seeing trends with the days
graph<-ggplot(time,aes(x=time$Start_Month, y=time$Start_Day,color=time$dayCount))+facet_wrap(time$Start_Year)+geom_point()+ scale_x_continuous(name = " ", breaks = c(1,2,3,4,5,6,7,8,9,10,11,12))+labs(x="Month",y="Day",color="Count",title = "Each day's accident number from 2017-2019")+ scale_colour_gradientn(colours = terrain.colors(10))
ggplotly(graph)
```

```{r}
#formatted to get dates on the x axis
time$Severity<-as.factor(time$Severity)
time$day<-ydm(time$Start_Date2)
#graphed progression line to show trend over time
graph<-ggplot()+geom_line(aes(x=time$day,y=time$dayCount,color="Count vs Day"
                              ),data = time,stat = "identity")+labs(x="Year",y="Count")+geom_smooth()

ggplotly(graph)
```

```{r}
#McKenna Code:

durationMapData <- Full_Duration %>% mutate(subregion=tolower(County), region=tolower(abbr2state(State))) %>% select(subregion, region, duration) %>% group_by(subregion,region) %>% summarize(medianDuration = median(duration)) %>% mutate(durationFactor = ifelse(medianDuration<1200,1,
                                              ifelse(medianDuration<2400, 2,
                                              ifelse(medianDuration<3600, 3,
                                              ifelse(medianDuration<4800, 4,
                                              ifelse(medianDuration<6000, 5, 6)))))) 
durationMapData$durationFactor <- as.factor(durationMapData$durationFactor)
colors <- c("steelblue1","steelblue2","steelblue3", "steelblue4","royalblue4","navyblue")
durationMapData %>% right_join(fullCounties, by=c("subregion","region")) %>% ggplot(aes(x=long,y=lat, fill=durationFactor)) + geom_polygon(aes(group=group)) + scale_fill_manual(name="Median Duration (min)", values=colors, labels=c("<20","20-40","40-60","60-80","80-100",">100")) +labs(title="Median Accident Duration by Location", x="Longitude", y="Latitude")



fullData %>% group_by(Severity) %>% summarize(c=n())

FullWeather <- fullData %>% mutate(relativeTemp = ifelse(Temperature.F. <= 20, "<20",
                                                 ifelse(Temperature.F. <= 40, "20-40", 
                                                 ifelse(Temperature.F. <= 60, "40-60",
                                                 ifelse(Temperature.F. <= 80, "60-80", ">80")))))
FullWeather <- FullWeather %>% mutate(relWind = ifelse(Wind_Speed.mph. <= 5, "<=5 mph",
                                                ifelse(Wind_Speed.mph. <= 10, "5-10 mph",
                                                ifelse(Wind_Speed.mph. <= 15, "10-15 mph", ">15 mph"))))

FullWeather$relativeTemp <- as.factor(FullWeather$relativeTemp)
FullWeather$relativeTemp <- factor(FullWeather$relativeTemp, levels=c("<20","20-40","40-60","60-80",">80"))
FullWeather$relWind <- as.factor(FullWeather$relWind)
FullWeather$relWind <- factor(FullWeather$relWind, levels=c("<=5 mph", "5-10 mph", "10-15 mph", ">15 mph"))
FullWeather$Severity <- as.factor(FullWeather$Severity)

FullWeather %>% filter(!is.na(relativeTemp) & !is.na(relWind)) %>%  ggplot(aes(x=relativeTemp, fill=Severity)) + geom_bar(position="stack") + labs(title= "Weather Conditions vs Frequency and Severity of Accidents", x="Temperature (F)", y="Number of Accidents") + facet_wrap(~relWind) + scale_y_continuous(labels=unit_format(unit="K", scale=1e-3)) + scale_fill_manual(values=c("goldenrod","steelblue2","steelblue3", "steelblue4"))

FullWeather$relativeTemp <- factor(FullWeather$relativeTemp, levels= rev(levels(FullWeather$relativeTemp)))

FullWeather %>% filter(!is.na(relativeTemp) & !is.na(relWind)) %>% ggplot(aes(x=Severity, fill=relativeTemp, y=1)) + geom_bar(stat="identity", position="fill") + facet_wrap(~relWind) + scale_fill_manual(values = c("goldenrod","steelblue1", "steelblue2","steelblue3", "steelblue4")) + labs(title="Weather vs Severity of Accidents", y="Temperature Proportion (%)")

```